dist: trusty
language: python
python:
  - "3.4"

install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g css-lint
  - sudo npm install -g eslint
  - pip install coala-bears
  - cd $TRAVIS_BUILD_DIR

script:
- coala --ci